### ISSUE TITLE
Is ignored pattern

### ISSUE THREAD

**Issue by Yomguithereal** [dcamilleri/node-map-directory#3]
Hello @dcamilleri. About the `is-ignored` module, we have the following:

``` js
module.exports = function isIgnored(fileName, ignoredDirs) {
  var isIg = false;
  for (var i = ignoredDirs.length - 1; i >= 0; i--) {
    if(fileName === ignoredDirs[i]) {
      isIg = true;
      break;
    }
  }
  return isIg;
};
```

Are you using a low-level pattern for perf reasons (why the reverse loop, why no length caching)?

First of all, do you really need the `break` and the `isIg` flag?
(By the way, why is the `isIg` variable the only one not to be perfectly explicit, why not `isIgnored`?)

``` js
module.exports = function isIgnored(fileName, ignoredDirs) {
  for (var i = ignoredDirs.length - 1; i >= 0; i--) {
    if(fileName === ignoredDirs[i]) {
      return true;
    }
  }
  return false;
};
```

Then, why not use either an `indexOf` or the `Array.prototype.some` function?

``` js
// indexOf (convoluted on purpose :-) )
module.exports = function isIgnored(fileName, ignoredDirs) {
  return !!~ignoredDirs.indexOf(fileName);
};

// Array.prototype.some
module.exports = function isIgnored(fileName, ignoredDirs) {
  return ignoredDirs.some(function(dir) {
    return dir === fileName;
  });
};
```

**Comment by dcamilleri** [comment]
Thanks for the explanation. I didn't know `Array.prototype.some` before, now I do!
